name: Build Photo Index

on:
  push:
    paths:
      - 'photos/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - name: Generate photos.json
        run: |
          find photos -type f \
          \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) \
          | sed 's#photos/##' \
          | jq -R -s -c 'split("\n")[:-1]' \
          > photos.json

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add photos.json
          git diff --staged --quiet || git commit -m "Update gallery"
          git push
